import Head from 'next/head'
import Banner from '../components/banner'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Card from '../components/card'
export default function Home() {

  const handleOnBannerBtnClick = () =>{
    console.log('button clicked')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner 
          buttonText="View stores nearby" 
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        <div className={styles.cardLayout}>
          <Card 
            name="DarkHorse Coffee" 
            imgUrl="/static/hero-image.png" 
            href="/coffee-store/DarkHorse"
            className={styles.card}
          />
        </div>
      </main>

    </div>
  )
}
